# Generated by Django 3.2 on 2022-08-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countofingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
