# Generated by Django 3.2 on 2022-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_countofingredient_ingredients'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='countofingredient',
            name='unique_ingredient_amount',
        ),
        migrations.AddConstraint(
            model_name='countofingredient',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipe'), name='unique_ingredient_amount'),
        ),
    ]
