# Generated by Django 3.2 on 2022-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220813_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='recipe',
            field=models.ManyToManyField(related_name='is_in_shopping_cart', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
